### ISSUE TITLE
Config for Gulp

### ISSUE THREAD

**Issue by qrczak** [posthtml/posthtml-pug#1]
What is proper Gulp config for posthtml-jade? I use like this:

``` js
var gulp = require('gulp');
var posthtml = require('gulp-posthtml');
gulp.task('jade', function() {
    var plugins = [
        require('posthtml-jade')({
            pretty: true
        })
    ];

    return gulp.src('jade/*.html')
        .pipe(posthtml(plugins))
        .pipe(gulp.dest('./'));
});
```

When I run task "gulp jade"
![4__qrczak_marcins-mac-mini____code_allegro__zsh_](https://cloud.githubusercontent.com/assets/97386/13717434/ca5638a0-e7e1-11e5-841c-1c7fe8ba6af7.png)

but nothing happens. No file is created. Nothing.

Any ideas?

**Comment by michael-ciniawsky** [comment]
hi, could you explain your setup more precise please, e.g if you use jade's include, block or mixins functionality you need to specify the `posthtml-jade({ filename: /* 'path/to/file' */ })` filename option during the fact that jade's includes etc. are relative to the file there were used in and therefore needed to know the file path.

A quick solution to this would be considering usage of [gulp-tap](https://npmjs.org/packages/gulp-tap) or [gulp-using](https://npmjs.org/packages/gulp-using) to get the current filename processed by the gulp stream and pass it to the plugin's filename option and it should work. See examples below.

**1. gulp-tap**

``` js
var gulp = require('gulp');
var tap = require('gulp-tap');
var posthtml = require('gulp-posthtml');

gulp.task('jade', function() {
    var file
    var plugins = [
        require('posthtml-jade')({
            pretty: true,
            filename: `${file}`
        })
    ];

    return gulp.src('jade/*.html')
        .pipe(tap(file => file = file.path))
        .pipe(posthtml(plugins))
        .pipe(gulp.dest('./'));
});
```

**2. gulp-using**

``` js
var gulp = require('gulp');
var using = require('gulp-using');
var posthtml = require('gulp-posthtml');

gulp.task('jade', function() {
    var plugins = [
        require('posthtml-jade')({
            pretty: true,
            filename: `${ using() }`
        })
    ];

    return gulp.src('jade/*.html')
        .pipe(posthtml(plugins))
        .pipe(gulp.dest('./'));
});
```

**Comment by michael-ciniawsky** [comment]
Did it work?

**Comment by qrczak** [comment]
Sorry, I'm out of the city. Tonight I'll check this out and let you know.

**Comment by qrczak** [comment]
Unfortunately still the same (in both cases), like on my screen before - no errors and no output file. Now I use gulp-jade with the same paths and without problems. But I want switch to post-html so I wanted to try your module. Have no idea where is the problem.

**Comment by michael-ciniawsky** [comment]
ok thats bad..., could you explain your setup a little please or publish a sample repo with the gulpfile html files etc?

**Comment by qrczak** [comment]
http://pastebin.com/Ucje7qsH - it's my playground now, so it's little messy there but it's works.
And if I run
`gulp jade`
it's not working
and the 
`jade/index.html`
file is http://pastebin.com/jRgHWFEz - nothing special just test

**Comment by michael-ciniawsky** [comment]
ok copied the jade file and tested it and it worked, but I set up another test give me a few moments please.. ;)

``` html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <title>Allegro</title>
    <link href="/css/style.css" rel="stylesheet">
  </head>
  <body>
    <div id="wrapper">
      <div id="bg">
        <div class="obrazek"><img id="img-top" src="img/nature1600.jpg"></div>
        <div class="main-section">
          <div class="left-col">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</div>
          <div class="right-col">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</div>
        </div>
        <div class="footer"><a href="google.com" class="button">Google</a></div>
      </div>
    </div>
  </body>
</html>
```

**Comment by qrczak** [comment]
OK, it's give me hope.. :)

**Comment by michael-ciniawsky** [comment]
please clone this repo [test-jade](https://github.com/michael-ciniawsky/test-jade) 
`git clone https://github.com/michael-ciniawsky/test-jade.git` and run 

``` bash
(sudo) npm i
```

&& 

```
gulp 
```

it should render your test file  `test.jade` &&  `test2.html` into the dest folder  both as `[name].html`.

**Comment by qrczak** [comment]
Your repository works indeed! Now I try implement it to my playground. Let you know later.

**Comment by qrczak** [comment]
I copy "jade" task from your to my gulpfile.js and it's works !!! :) The funny thing is this "jade" task is almost the same like your second example from one of yours previous post. Magic ??? :)
Anyway thanks man :)

**Comment by michael-ciniawsky** [comment]
i couldn't see any issue in your gulpfile myself, seems to be dark computional magic awesome :D... you can refactor your templates task if you prefer posthtml-jade don't cares about the file ext just renders/compiles the string given to it(also ignores html markup and just pass it to the next plugin in the chain), but you need to rename the file ext afterwards with gulp-rename(when not `.html`), possibly an if condition checking the ext when intermixing html and jade files in your src folder. You're welcome if anything breaks please file an issue closing this one now. By the way the notification and error reporting you set up looks pretty interesting, hopefully i can set this up myself without blessedness of the dark wizards ;)

**Comment by qrczak** [comment]
> you can refactor your templates task if you prefer posthtml-jade don't cares about the file ext just renders/compiles the string given to it(also ignores html markup and just pass it to the next plugin in the chain), but you need to rename the file ext afterwards with gulp-rename(when not .html), possibly an if condition checking the ext when intermixing html and jade files in your src folder.

That's fine.I choose *.jade to *.html it's better for me. So I gonna close this issue :)

> hopefully i can set this up myself without blessedness of the dark wizards ;)

Hehe, yeah :)
