### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml-pug#5]
Jade reports dependencies with its return value, and some build systems (such as webpack) take advantage of this information. For example, in development when watching your site, if you make changes to a jade file that is `include`'ed into a couple other files, since it's aware of the dependencies it can reload and update all the affected files.

`postcss-import` has this same issue, and has dealt with it by adding [an `addDependencyTo` option](https://github.com/postcss/postcss-import#adddependencyto), which allows dependencies to be tracked correctly through webpack and any other build system that tracks dependencies.

Would you consider adding an option like this to posthtml-jade? If so, I'd be happy to submit a pull request to add this myself 😁

**Comment by michael-ciniawsky** [comment]
if you know how a addDependecyTo implementation would look like, please make are PR
