### ISSUE TITLE
"While" loop breaks jade

### ISSUE THREAD

**Issue by allanwhite** [posthtml/posthtml-pug#8]
I'm trying to create a simple `while` loop, and it breaks jade (does not compile) every time.

This example, from the [jade-lang](http://jade-lang.com/reference/iteration/) page:

```
- var n = 0
ul
    while n < 4
        li= n++
```

Does not render. It also fails silently when `spike watch` is running, with no errors. 

Sample file in question [here](https://github.com/allanwhite/spike-webpack/blob/master/views/guide/content-lists.jade).

**Comment by jescalan** [comment]
I bet it's the `<` character, as seen in this caveat: https://github.com/posthtml/posthtml-jade#raw-html

**Comment by jescalan** [comment]
Try switching this character just to see if it renders

**Comment by allanwhite** [comment]
I couldn't get it to work, @jescalan. I do understand why the `<>` characters won't render inside a string of text, but javascript operations like if/else and while should be in "js mode", right? Otherwise, how else can statements be evaluated? For/each works ok, for example.

**Comment by jescalan** [comment]
Sorry I probably didn't explain it clearly. At the moment, the way that the jade plugin works is that the entire source is passed through an html parser first, regardless of the fact that it is clearly not html (no "js mode" here). If there are no tags or html-like entities, the parser returns it as just one gigantic string. This plugin then takes the first node in the parser's output, assumes that it's a string containing the entire source, renders it, and adds it back into the tree. If the html parser finds any even tiny piece that it can parse, the entire plugin silently fails, and gives you back an un-rendered string.

This is far from ideal for sure, I am working hard to replace this with something more suitable, I promise. For now the only way to avoid these issues and move forward is to work around them, or wait until the posthtml refactor is finished and use [sugarml](https://github.com/posthtml/sugarml).

**Comment by allanwhite** [comment]
Thanks for explaining, @jescalan. I'll close this issue.

**Comment by jescalan** [comment]
You don't have to close it, it still is definitely an issue haha
